# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  build-test-monitor:
      docker:
        # specify the version
        - image: circleci/golang:1.13

      steps:
        - checkout
        - run: go test -v
        - snyk/scan:
            fail-on-issues: true
            monitor-on-build: true
            token-variable: SNYK_TOKEN
        - run: ./generate-binaries.sh
        - persist_to_workspace:
            root: .
            paths:
              - dist/*

  build-test:
      docker:
        # specify the version
        - image: circleci/golang:1.13

      steps:
        - checkout
        - run: go test -v
        - snyk/scan:
            fail-on-issues: false
            monitor-on-build: false
            token-variable: SNYK_TOKEN
            additional-arguments: --json-file-output=snykTestResults.json
        - run: ./snyk-prevent-gh-commit-status-linux ./snykTestResults.json ${GITHUB_TOKEN} ${CIRCLE_PROJECT_USERNAME} ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_SHA1}

  build-test-from-fork:
      docker:
        # specify the version
        - image: circleci/golang:1.13

      steps:
        - checkout
        - run: go test -v

  publish-github-release:
    docker:
      - image: gcr.io/snyk-technical-services/cicd-github
        auth:
          username: _json_key
          password: $GCLOUD_GCR_SNYK_TS_READER
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sha256sum dist/snyk-jira-sync-linux > dist/snyk-jira-sync-linux.sha256
      - run: sha256sum dist/snyk-jira-sync-macos > dist/snyk-jira-sync-macos.sha256
      - run: sha256sum dist/snyk-jira-sync-win.exe > dist/snyk-jira-sync-win.exe.sha256
      - run:
          name: "Publish Release on GitHub"
          command: |    
            VERSIONJUMP=$(git log --oneline -1 --pretty=%B | cat | grep -E 'minor|major|patch' | awk -F ':' '{print $1}')   
            VERSION=$(/workdir/nextver.sh "$VERSIONJUMP")
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} dist/

workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test-monitor
  build-test-monitor-publish:
    jobs:
      - build-test-monitor:
          filters:
            branches:
              only:
                  - master
      - publish-github-release:
          requires:
            - build-test-monitor
          filters:
            branches:
              only:
                - master
  build-test:
      jobs:
        - build-test:
            filters:
              branches:
                ignore:
                  - master
                  - /pull\/[0-9]+/
        - build-test-from-fork:
            filters:
              branches:
                only:
                  - /pull\/[0-9]+/
